[project]
name = "repos-management"
version = "0.1.0"
description = "Manage multiple repositories with ease"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
]
