#!/usr/bin/env python3
"""
Convert README.md -> readme.toml (bidirectional converter part 2).

This is the reverse converter that parses Markdown files generated by
convert_toml_to_readme.py and reconstructs the original TOML structure.

Design principles:
1. Use H2 sections (## Title) to locate [[sections]]
2. Use author attribution (> 文 / ...) to locate section item boundaries
3. Use HTML comments (<!-- TOML-ITEM: ... -->) as placeholders for items without authors
4. Preserve round-trip idempotency: TOML -> MD -> TOML should be lossless

Supports two schema types:
- normal: Single course with [[sections]]
- multi-project: Multiple courses with [[courses]]
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# Python 3.11+ has tomllib in stdlib, otherwise use tomli
try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore

# For writing TOML
try:
    import tomli_w  # type: ignore
except ImportError:
    tomli_w = None  # Will fall back to manual formatting


# ============================================================================
# Data Models
# ============================================================================


@dataclass
class Author:
    """Author attribution model."""

    name: str = ""
    link: str = ""
    date: str = ""

    def to_toml(self) -> dict:
        """Convert to TOML dict format."""
        return {"name": self.name, "link": self.link, "date": self.date}

    @classmethod
    def from_toml(cls, data: dict | str) -> "Author":
        """Create from TOML data."""
        if isinstance(data, str):
            return cls(name=data)
        return cls(
            name=data.get("name", ""),
            link=data.get("link", ""),
            date=data.get("date", ""),
        )


@dataclass
class SectionItem:
    """A single item within a section."""

    content: str = ""
    author: Author | list[Author] | None = None  # Single or multiple authors
    item_id: str = ""  # From <!-- TOML-ITEM: id="..." -->
    topic: str = ""  # From <!-- TOML-ITEM: topic="..." -->
    has_author: bool = False  # From <!-- TOML-ITEM: has_author="true" -->
    author_is_list: bool = False  # From <!-- TOML-ITEM: author_type="list" -->

    def to_toml(self) -> dict:
        """Convert to TOML dict format."""
        result = {}
        if self.content:
            result["content"] = self.content
        if self.topic:
            result["topic"] = self.topic
        if self.author is not None:
            if isinstance(self.author, list):
                result["author"] = [a.to_toml() for a in self.author]
            else:
                result["author"] = self.author.to_toml()
        elif self.has_author:
            # Empty author dict preserved via comment
            result["author"] = {"name": "", "link": "", "date": ""}
        return result


@dataclass
class Lecturer:
    """Lecturer with reviews."""

    name: str = ""
    reviews: list[SectionItem] = field(default_factory=list)

    def to_toml(self) -> dict:
        """Convert to TOML dict format."""
        result: dict[str, Any] = {"name": self.name}
        if self.reviews:
            result["reviews"] = [r.to_toml() for r in self.reviews]
        return result


@dataclass
class LecturersBlock:
    """New lecturers block.

    Schema:

    [lecturers]
      [[lecturers.intro]]     (list[SectionItem])
      [[lecturers.items]]     (list[Lecturer])
      [[lecturers.summary]]   (list[SectionItem])

    Legacy schema is represented by putting data into `items`.
    """

    intro: list[SectionItem] = field(default_factory=list)
    items: list[Lecturer] = field(default_factory=list)
    summary: list[SectionItem] = field(default_factory=list)

    def is_empty(self) -> bool:
        return not self.intro and not self.items and not self.summary


@dataclass
class Section:
    """A section with title and items."""

    title: str = ""
    items: list[SectionItem] = field(default_factory=list)

    # Special: 授课教师 section
    lecturers: list[Lecturer] = field(default_factory=list)  # legacy parsed shape
    lecturers_block: LecturersBlock | None = None  # new parsed shape

    def to_toml(self) -> dict:
        """Convert to TOML dict format."""
        if self.lecturers or self.lecturers_block is not None:
            return {}
        result: dict[str, Any] = {"title": self.title}
        if self.items:
            result["items"] = [i.to_toml() for i in self.items]
        return result


@dataclass
class Course:  # For multi-project schema
    """A course within a multi-project repo."""

    name: str = ""
    code: str = ""
    reviews: list[SectionItem] = field(default_factory=list)
    teachers: list[Lecturer] = field(default_factory=list)
    sections: list[Section] = field(default_factory=list)

    def to_toml(self) -> dict:
        """Convert to TOML dict format."""
        result: dict[str, Any] = {}
        if self.name:
            result["name"] = self.name
        if self.code:
            result["code"] = self.code
        if self.reviews:
            result["reviews"] = [r.to_toml() for r in self.reviews]
        if self.teachers:
            result["teachers"] = [t.to_toml() for t in self.teachers]
        if self.sections:
            result["sections"] = [s.to_toml() for s in self.sections]
        return result


@dataclass
class Document:
    """Root document model."""

    course_name: str = ""
    course_code: str = ""
    repo_type: str = "normal"  # "normal" or "multi-project"
    description: str = ""
    sections: list[Section] = field(default_factory=list)

    # Lecturers (new schema)
    lecturers: LecturersBlock = field(default_factory=LecturersBlock)

    courses: list[Course] = field(default_factory=list)  # For multi-project
    misc: dict | list[dict] = field(default_factory=dict)  # e.g. MOOC misc

    # Metadata from badges
    credits: str = ""
    hours: str = ""
    grading: str = ""


# ============================================================================
# Parsing Utilities
# ============================================================================


def normalize_text(text: str) -> str:
    """Normalize text: strip, dedent, normalize line endings."""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    lines = text.split("\n")
    if len(lines) > 1:
        min_indent = float("inf")
        for line in lines[1:]:
            if line.strip():
                indent = len(line) - len(line.lstrip())
                min_indent = min(min_indent, indent)
        if min_indent > 0 and min_indent != float("inf"):
            lines = [lines[0]] + [
                line[min_indent:] if line.strip() else line for line in lines[1:]
            ]
    return "\n".join(lines).strip()


def decode_shields_component(s: str) -> str:
    """Decode a shields.io URL path component."""
    s = s.replace("%20", " ")
    s = s.replace("%25", "%")
    s = re.sub(r"--", "-", s)
    return s


_DATE_RE = re.compile(r"\d{4}-\d{2}(?:-\d{2})?")


def parse_author_line(line: str) -> list[Author] | Author | None:
    """Parse author attribution line.

    Returns:
    - None if not an author line
    - Author for single author
    - list[Author] for multiple authors

    Formats:
    - > 文 / [name](link)，YYYY-MM
    - > 文 / [name](link)
    - > 文 / 佚名
    - > 文 / 佚名，YYYY-MM
    - > 文 / Name，YYYY-MM  (Chinese comma)
    - > 文 / Name, YYYY-MM  (English comma)
    - > 文 / [name1](link1)，date1，[name2](link2)，date2  (multi-author)
    """
    line = line.strip()
    if not line.startswith(">"):
        return None

    content = line[1:].strip()

    if not content.startswith("文 /"):
        return None

    content = content[3:].strip()  # Remove "文 /"

    if not content:
        return Author()

    authors: list[Author] = []
    remaining = content

    while remaining:
        remaining = remaining.strip()
        if not remaining:
            break

        # Skip leading separators
        if remaining[0] in (",", "，"):
            remaining = remaining[1:].strip()
            continue

        # Try linked author: [name](link)
        m = re.match(r"\[([^\]]*)\]\(([^)]*)\)", remaining)
        if m:
            name = m.group(1)
            link = m.group(2)
            remaining = remaining[m.end() :].strip()
            date = ""

            # Check for comma + date
            if remaining and remaining[0] in (",", "，"):
                after_comma = remaining[1:].strip()
                dm = _DATE_RE.match(after_comma)
                if dm:
                    date = dm.group(0)
                    remaining = after_comma[dm.end() :].strip()
                else:
                    remaining = after_comma

            authors.append(Author(name=name, link=link, date=date))
            continue

        # Try 佚名
        if remaining.startswith("佚名"):
            remaining = remaining[2:].strip()
            date = ""

            if remaining and remaining[0] in (",", "，"):
                after_comma = remaining[1:].strip()
                dm = _DATE_RE.match(after_comma)
                if dm:
                    date = dm.group(0)
                    remaining = after_comma[dm.end() :].strip()
                else:
                    remaining = after_comma

            authors.append(Author(name="佚名", link="", date=date))
            continue

        # Try plain name (no link)
        name_m = re.match(r"^([^,，\[\]]+)", remaining)
        if name_m:
            name_text = name_m.group(1).strip()
            remaining = remaining[name_m.end() :].strip()
            date = ""

            # Check if this looks like a date
            if _DATE_RE.fullmatch(name_text):
                if authors:
                    authors[-1].date = name_text
                continue

            # Check for comma + date after name
            if remaining and remaining[0] in (",", "，"):
                after_comma = remaining[1:].strip()
                dm = _DATE_RE.match(after_comma)
                if dm:
                    date = dm.group(0)
                    remaining = after_comma[dm.end() :].strip()
                else:
                    remaining = after_comma

            authors.append(Author(name=name_text, link="", date=date))
            continue

        # Fallback
        if remaining:
            authors.append(Author(name=remaining, link="", date=""))
        break

    if not authors:
        return Author()

    if len(authors) == 1:
        return authors[0]

    return authors


def parse_badge_url(url: str) -> tuple[str, str, str]:
    """Parse shields.io badge URL."""
    m = re.search(r"/badge/(.+)$", url)
    if not m:
        return ("", "", "")

    path = m.group(1)
    path = path.replace("--", "\x00ENCODED_DASH\x00")
    parts = path.split("-")
    parts = [p.replace("\x00ENCODED_DASH\x00", "-") for p in parts]

    if len(parts) >= 3:
        return (
            decode_shields_component(parts[0]),
            decode_shields_component(parts[1]),
            decode_shields_component(parts[2]),
        )
    elif len(parts) == 2:
        return (
            decode_shields_component(parts[0]),
            "",
            decode_shields_component(parts[1]),
        )
    elif len(parts) == 1:
        return (decode_shields_component(parts[0]), "", "")

    return ("", "", "")


def parse_toml_comment(line: str) -> dict[str, str]:
    """Parse HTML comment containing TOML metadata.

    Formats:
    - <!-- TOML-SECTION: title="..." type="..." -->
    - <!-- TOML-ITEM: id="..." topic="..." author_type="list" has_author="true" -->
    - <!-- TOML-META: repo_type="normal" -->
    - <!-- TOML-LECTURERS: part="intro|items|summary" -->
    """
    m = re.match(r"<!--\s*TOML-(\w+):\s*(.+?)\s*-->", line.strip())
    if not m:
        return {}

    comment_type = m.group(1).lower()
    content = m.group(2)

    result = {"type": comment_type}

    for pair_m in re.finditer(r'(\w+)="([^"]*)"', content):
        result[pair_m.group(1)] = pair_m.group(2)

    return result


# ============================================================================
# Main Parser
# ============================================================================


class MarkdownParser:
    """Parse Markdown back to TOML structure."""

    def __init__(self, content: str):
        self.content = content
        self.lines = content.split("\n")
        self.pos = 0
        self.doc = Document()

    def parse(self) -> Document:
        """Parse the entire document."""
        # Check for TOML-META comment (repo_type)
        for line in self.lines:
            comment = parse_toml_comment(line)
            if comment.get("type") == "meta":
                if "repo_type" in comment:
                    self.doc.repo_type = comment["repo_type"]
                break

        # Extract H1 title
        self._parse_title()

        # Skip TOML-META comment if present
        while self.pos < len(self.lines):
            line = self.lines[self.pos].strip()
            if line.startswith("<!-- TOML-META:"):
                self.pos += 1
                continue
            break

        # Parse badges
        self._parse_badges()

        # Parse sections
        if self.doc.repo_type == "multi-project":
            # Multi-project handles its own description parsing
            # (description may contain ## headers, so _parse_description would break)
            self._parse_multi_project()
        else:
            self._parse_description()
            self._parse_sections()

        return self.doc

    def _parse_title(self):
        """Parse H1 title: # CODE - Name"""
        for i, line in enumerate(self.lines):
            if line.startswith("# "):
                title = line[2:].strip()
                parts = title.split(" - ", 1)
                if len(parts) == 2:
                    self.doc.course_code = parts[0].strip()
                    self.doc.course_name = parts[1].strip()
                else:
                    self.doc.course_name = title
                self.pos = i + 1
                return

    def _parse_badges(self):
        """Parse shields.io badges.

        Badges marked with ``<!-- TOML-BADGES: source="grades_summary" -->``
        come from an external grades_summary.toml and should NOT be written
        back to the course TOML (they are regenerated on every forward pass).
        Only badges from ``source="basic_info"`` (or unmarked legacy badges)
        are persisted to the ``基本信息`` section in TOML.
        """
        badges = []
        badge_source = "basic_info"  # default for legacy / unmarked READMEs

        for i in range(self.pos, len(self.lines)):
            line = self.lines[i]

            # Detect badge source marker
            badge_comment = parse_toml_comment(line)
            if badge_comment.get("type") == "badges":
                badge_source = badge_comment.get("source", "basic_info")
                self.pos = i + 1
                continue

            m = re.match(
                r"!\[([^\]]*)\]\((https://img\.shields\.io/badge/[^)]+)\)", line
            )
            if m:
                alt = m.group(1)
                url = m.group(2)
                label, message, color = parse_badge_url(url)
                badges.append((alt, label, message, color))
                self.pos = i + 1
                continue

            if line.strip() and not line.startswith("<!--"):
                break

            self.pos = i + 1

        # Skip storing badge data if they come from external grades_summary
        if badge_source == "grades_summary":
            return

        for alt, label, message, color in badges:
            if label == "学分":
                self.doc.credits = message
            elif label in ("学时构成", "学时分布"):
                self.doc.hours = message
            elif label == "成绩构成":
                pass
            elif message:
                if self.doc.grading:
                    self.doc.grading += f" | {label} {message}"
                else:
                    self.doc.grading = f"{label} {message}"

    def _parse_description(self):
        """Parse description paragraphs before first H2."""
        desc_lines = []

        for i in range(self.pos, len(self.lines)):
            line = self.lines[i]

            if line.startswith("## "):
                self.pos = i
                break

            if not desc_lines and not line.strip():
                continue

            desc_lines.append(line)
        else:
            self.pos = len(self.lines)

        self.doc.description = normalize_text("\n".join(desc_lines))

    def _parse_sections(self):
        """Parse all H2 sections."""
        while self.pos < len(self.lines):
            line = self.lines[self.pos]

            if line.startswith("## "):
                section = self._parse_section()
                if section:
                    if section.title == "授课教师":
                        if section.lecturers_block is not None:
                            self.doc.lecturers = section.lecturers_block
                        else:
                            # Legacy: lecturers parsed as plain list
                            self.doc.lecturers.items = section.lecturers
                    else:
                        self.doc.sections.append(section)
            else:
                self.pos += 1

    def _parse_section(self) -> Section | None:
        """Parse a single H2 section."""
        title_line = self.lines[self.pos]
        title = title_line[3:].strip()
        self.pos += 1

        section = Section(title=title)

        # Check for TOML-SECTION comment
        if self.pos < len(self.lines):
            comment_data = parse_toml_comment(self.lines[self.pos])
            if comment_data.get("type") == "section":
                if "title" in comment_data:
                    section.title = comment_data["title"]
                self.pos += 1

        # Special handling for 授课教师
        if title == "授课教师":
            section.lecturers_block = self._parse_lecturers_block()
            if section.lecturers_block is None:
                section.lecturers = []
            return section

        # Parse items until next H2 or EOF
        current_item = SectionItem()
        content_lines: list[str] = []

        while self.pos < len(self.lines):
            line = self.lines[self.pos]

            if line.startswith("## "):
                break

            # Check for TOML-ITEM comment
            comment_data = parse_toml_comment(line)
            if comment_data.get("type") == "item":
                # Save previous item
                if (
                    content_lines
                    or current_item.topic
                    or current_item.item_id
                    or current_item.has_author
                ):
                    current_item.content = normalize_text("\n".join(content_lines))
                    if (
                        current_item.content
                        or current_item.topic
                        or current_item.item_id
                        or current_item.has_author
                    ):
                        section.items.append(current_item)
                    content_lines = []

                current_item = SectionItem()
                if "id" in comment_data:
                    current_item.item_id = comment_data["id"]
                if "topic" in comment_data:
                    current_item.topic = comment_data["topic"]
                if comment_data.get("has_author") == "true":
                    current_item.has_author = True
                if comment_data.get("author_type") == "list":
                    current_item.author_is_list = True
                self.pos += 1
                continue

            # Check for author attribution
            parsed_author = parse_author_line(line)
            if parsed_author is not None:
                current_item.content = normalize_text("\n".join(content_lines))
                if isinstance(parsed_author, list):
                    current_item.author = parsed_author
                elif current_item.author_is_list:
                    current_item.author = [parsed_author]
                else:
                    current_item.author = parsed_author
                if (
                    current_item.content
                    or current_item.author
                    or current_item.topic
                    or current_item.has_author
                ):
                    section.items.append(current_item)
                current_item = SectionItem()
                content_lines = []
                self.pos += 1
                continue

            content_lines.append(line)
            self.pos += 1

        # Save last item
        if (
            content_lines
            or current_item.topic
            or current_item.item_id
            or current_item.has_author
        ):
            current_item.content = normalize_text("\n".join(content_lines))
            if (
                current_item.content
                or current_item.topic
                or current_item.item_id
                or current_item.has_author
            ):
                section.items.append(current_item)

        return section

    def _parse_lecturers_block(self) -> LecturersBlock:
        """Parse '授课教师' into the new lecturers block.

        If the file is legacy (no TOML-LECTURERS markers), we parse legacy lecturer list
        and store it into `items`.
        """

        # Detect whether this README contains new lecturers markers in this section
        scan = self.pos
        has_marker = False
        while scan < len(self.lines):
            ln = self.lines[scan]
            if ln.startswith("## "):
                break
            c = parse_toml_comment(ln)
            if c.get("type") == "lecturers":
                has_marker = True
                break
            scan += 1

        if not has_marker:
            block = LecturersBlock()
            block.items = self._parse_lecturers_items_until_boundary()
            return block

        block = LecturersBlock()

        while self.pos < len(self.lines):
            line = self.lines[self.pos]
            if line.startswith("## "):
                break

            c = parse_toml_comment(line)
            if c.get("type") == "lecturers":
                part = (c.get("part") or "").strip().lower()
                self.pos += 1

                if part == "intro":
                    block.intro.extend(
                        self._parse_lecturers_free_items_until_boundary()
                    )
                    continue
                if part == "items":
                    block.items.extend(self._parse_lecturers_items_until_boundary())
                    continue
                if part == "summary":
                    block.summary.extend(
                        self._parse_lecturers_free_items_until_boundary()
                    )
                    continue
                continue

            # Tolerate stray blank lines / human edits
            self.pos += 1

        return block

    def _parse_lecturers_free_items_until_boundary(self) -> list[SectionItem]:
        """Parse intro/summary items until next lecturers marker / lecturer list / next section."""

        items: list[SectionItem] = []
        current_item = SectionItem()
        content_lines: list[str] = []

        def _flush_item() -> None:
            nonlocal current_item, content_lines
            if not (
                content_lines
                or current_item.item_id
                or current_item.topic
                or current_item.has_author
                or current_item.author
            ):
                current_item = SectionItem()
                content_lines = []
                return
            current_item.content = normalize_text("\n".join(content_lines))
            if (
                current_item.content
                or current_item.author
                or current_item.topic
                or current_item.has_author
            ):
                items.append(current_item)
            current_item = SectionItem()
            content_lines = []

        while self.pos < len(self.lines):
            line = self.lines[self.pos]
            if line.startswith("## "):
                break
            if line.strip().startswith("<!-- TOML-LECTURERS:"):
                break
            if re.match(r"^- [^\s]", line):
                break

            comment_data = parse_toml_comment(line)
            if comment_data.get("type") == "item":
                _flush_item()
                current_item = SectionItem()
                if "id" in comment_data:
                    current_item.item_id = comment_data["id"]
                if "topic" in comment_data:
                    current_item.topic = comment_data["topic"]
                if comment_data.get("has_author") == "true":
                    current_item.has_author = True
                if comment_data.get("author_type") == "list":
                    current_item.author_is_list = True
                self.pos += 1
                continue

            parsed_author = parse_author_line(line)
            if parsed_author is not None:
                current_item.content = normalize_text("\n".join(content_lines))
                if isinstance(parsed_author, list):
                    current_item.author = parsed_author
                elif current_item.author_is_list:
                    current_item.author = [parsed_author]
                else:
                    current_item.author = parsed_author
                if (
                    current_item.content
                    or current_item.author
                    or current_item.topic
                    or current_item.has_author
                ):
                    items.append(current_item)
                current_item = SectionItem()
                content_lines = []
                self.pos += 1
                continue

            # Skip leading blank lines
            if not line.strip() and not content_lines and not current_item.item_id:
                self.pos += 1
                continue

            content_lines.append(line)
            self.pos += 1

        _flush_item()
        return items

    def _parse_lecturers_items_until_boundary(self) -> list[Lecturer]:
        """Parse lecturer bullet list until next lecturers marker / next section."""

        lecturers: list[Lecturer] = []
        current_lecturer: Lecturer | None = None
        current_review: SectionItem | None = None
        content_lines: list[str] = []

        def _flush_review() -> None:
            nonlocal content_lines, current_review
            if current_lecturer is None:
                return
            if current_review is not None:
                current_review.content = normalize_text("\n".join(content_lines))
                if (
                    current_review.content
                    or current_review.author
                    or current_review.has_author
                ):
                    current_lecturer.reviews.append(current_review)
                current_review = None
            elif content_lines:
                review = SectionItem()
                review.content = normalize_text("\n".join(content_lines))
                if review.content:
                    current_lecturer.reviews.append(review)
            content_lines = []

        while self.pos < len(self.lines):
            line = self.lines[self.pos]

            if line.startswith("## "):
                break
            if line.strip().startswith("<!-- TOML-LECTURERS:"):
                break

            # Check for TOML-ITEM comment
            comment_data = parse_toml_comment(line)
            if comment_data.get("type") == "item":
                _flush_review()
                current_review = SectionItem()
                if "id" in comment_data:
                    current_review.item_id = comment_data["id"]
                if "topic" in comment_data:
                    current_review.topic = comment_data["topic"]
                if comment_data.get("has_author") == "true":
                    current_review.has_author = True
                if comment_data.get("author_type") == "list":
                    current_review.author_is_list = True
                self.pos += 1
                continue

            # Lecturer name (top-level list item)
            if re.match(r"^- [^\s]", line):
                _flush_review()
                if current_lecturer:
                    lecturers.append(current_lecturer)

                current_lecturer = Lecturer()
                current_lecturer.name = line[2:].strip()
                content_lines = []
                current_review = None
                self.pos += 1
                continue

            # Review content (nested list item with 2-space indent)
            if line.startswith("  - "):
                content_lines.append(line[4:])
                self.pos += 1
                continue

            # Indented TOML-ITEM comment (within lecturer)
            if line.strip().startswith("<!-- TOML-ITEM:"):
                comment_data = parse_toml_comment(line.strip())
                if comment_data.get("type") == "item":
                    _flush_review()
                    current_review = SectionItem()
                    if "id" in comment_data:
                        current_review.item_id = comment_data["id"]
                    if "topic" in comment_data:
                        current_review.topic = comment_data["topic"]
                    if comment_data.get("has_author") == "true":
                        current_review.has_author = True
                    if comment_data.get("author_type") == "list":
                        current_review.author_is_list = True
                    self.pos += 1
                    continue

            # Further nested content / author line (4+ spaces)
            if line.startswith("    "):
                parsed_author = parse_author_line(line)
                if parsed_author is not None and current_lecturer is not None:
                    if current_review is not None:
                        current_review.content = normalize_text(
                            "\n".join(content_lines)
                        )
                        if isinstance(parsed_author, list):
                            current_review.author = parsed_author
                        elif current_review.author_is_list:
                            current_review.author = [parsed_author]
                        else:
                            current_review.author = parsed_author
                        if (
                            current_review.content
                            or current_review.author
                            or current_review.has_author
                        ):
                            current_lecturer.reviews.append(current_review)
                        current_review = None
                    else:
                        review = SectionItem()
                        review.content = normalize_text("\n".join(content_lines))
                        if isinstance(parsed_author, list):
                            review.author = parsed_author
                        else:
                            review.author = parsed_author
                        if review.content or review.author:
                            current_lecturer.reviews.append(review)
                    content_lines = []
                    self.pos += 1
                    continue
                content_lines.append(line[2:])
                self.pos += 1
                continue

            # Author attribution at normal indent
            parsed_author = parse_author_line(line)
            if parsed_author is not None and current_lecturer is not None:
                if current_review is not None:
                    current_review.content = normalize_text("\n".join(content_lines))
                    if isinstance(parsed_author, list):
                        current_review.author = parsed_author
                    elif current_review.author_is_list:
                        current_review.author = [parsed_author]
                    else:
                        current_review.author = parsed_author
                    if (
                        current_review.content
                        or current_review.author
                        or current_review.has_author
                    ):
                        current_lecturer.reviews.append(current_review)
                    current_review = None
                else:
                    review = SectionItem()
                    review.content = normalize_text("\n".join(content_lines))
                    if isinstance(parsed_author, list):
                        review.author = parsed_author
                    else:
                        review.author = parsed_author
                    if review.content or review.author:
                        current_lecturer.reviews.append(review)
                content_lines = []
                self.pos += 1
                continue

            if not line.strip():
                self.pos += 1
                continue

            self.pos += 1

        if current_lecturer:
            _flush_review()
            lecturers.append(current_lecturer)

        return lecturers

    # Legacy parser kept for compatibility with old workflow / tests
    def _parse_lecturers(self) -> list[Lecturer]:
        """Parse lecturers section with nested reviews."""
        return self._parse_lecturers_items_until_boundary()

    def _parse_multi_project(self):
        """Parse multi-project structure."""
        current_course: Course | None = None
        description_lines: list[str] = []

        # Pre-scan: check if TOML-COURSES-START marker exists anywhere
        has_courses_marker = any(
            line.strip() == "<!-- TOML-COURSES-START -->"
            for line in self.lines[self.pos :]
        )
        courses_started = False

        while self.pos < len(self.lines):
            line = self.lines[self.pos]

            # Detect courses start marker — everything before it is description
            if line.strip() == "<!-- TOML-COURSES-START -->":
                if description_lines:
                    self.doc.description = normalize_text("\n".join(description_lines))
                    description_lines = []
                courses_started = True
                self.pos += 1
                continue

            # Before courses start, collect description lines
            if not courses_started:
                # If we hit a ## heading and there is NO TOML-COURSES-START marker
                # anywhere in the file, treat first ## as implicit courses start
                # (fallback for human-edited READMEs that never had the marker).
                if line.startswith("## ") and not has_courses_marker:
                    if description_lines:
                        self.doc.description = normalize_text(
                            "\n".join(description_lines)
                        )
                        description_lines = []
                    courses_started = True
                    # Do NOT advance self.pos — let the ## handler below pick it up
                    continue

                # Skip blank lines at the very start
                if not description_lines and not line.strip():
                    self.pos += 1
                    continue
                description_lines.append(line)
                self.pos += 1
                continue

            # Detect misc section marker
            if line.strip() == "<!-- TOML-MISC -->":
                # Save current course and parse misc
                if current_course is not None:
                    self.doc.courses.append(current_course)
                    current_course = None
                self.pos += 1
                self._parse_misc()
                continue

            if line.startswith("## "):
                if current_course is not None:
                    self.doc.courses.append(current_course)

                header = line[3:].strip()
                current_course = Course()
                self.pos += 1

                # Check for TOML-COURSE comment with exact code/name
                if self.pos < len(self.lines):
                    m = re.match(
                        r'<!--\s*TOML-COURSE:\s*code="([^"]*)"\s*name="([^"]*)"\s*-->',
                        self.lines[self.pos].strip(),
                    )
                    if m:
                        current_course.code = m.group(1)
                        current_course.name = m.group(2)
                        self.pos += 1
                        continue

                # Fallback: split header on ' - '
                parts = header.split(" - ", 1)
                if len(parts) == 2:
                    current_course.code = parts[0].strip()
                    current_course.name = parts[1].strip()
                else:
                    current_course.name = header
                continue

            if line.startswith("### ") and current_course is not None:
                sub_title = line[4:].strip()
                self.pos += 1

                # Check if next line is a TOML-COURSE-REVIEWS marker
                is_reviews = False
                if (
                    self.pos < len(self.lines)
                    and self.lines[self.pos].strip() == "<!-- TOML-COURSE-REVIEWS -->"
                ):
                    is_reviews = True
                    self.pos += 1  # skip the marker

                # Determine section title by removing course prefix
                prefix = ""
                if current_course.code and current_course.name:
                    prefix = f"{current_course.code} - {current_course.name} - "
                elif current_course.code:
                    prefix = f"{current_course.code} - "
                elif current_course.name:
                    prefix = f"{current_course.name} - "

                section_title = sub_title
                if prefix and sub_title.startswith(prefix):
                    section_title = sub_title[len(prefix) :]
                elif " - " in sub_title:
                    parts = sub_title.rsplit(" - ", 1)
                    section_title = parts[-1]

                if section_title == "授课教师":
                    current_course.teachers = self._parse_multi_project_teachers()
                elif is_reviews:
                    # Parse as flat review items with topic = section_title
                    review_items = self._parse_multi_project_review_items(section_title)
                    current_course.reviews.extend(review_items)
                else:
                    section = self._parse_multi_project_section(section_title)
                    if section:
                        current_course.sections.append(section)
                continue

            m = re.match(
                r"!\[([^\]]*)\]\((https://img\.shields\.io/badge/[^)]+)\)", line
            )
            if m and current_course is not None:
                self.pos += 1
                continue

            self.pos += 1

        if current_course is not None:
            self.doc.courses.append(current_course)

    def _parse_multi_project_teachers(self) -> list[Lecturer]:
        """Parse teacher list within a multi-project course subsection."""
        teachers: list[Lecturer] = []
        current_teacher: Lecturer | None = None
        content_lines: list[str] = []

        while self.pos < len(self.lines):
            line = self.lines[self.pos]

            if line.startswith("## ") or line.startswith("### "):
                break

            if re.match(r"^- [^\s]", line):
                if current_teacher:
                    if content_lines:
                        review = SectionItem()
                        review.content = normalize_text("\n".join(content_lines))
                        if review.content:
                            current_teacher.reviews.append(review)
                        content_lines = []
                    teachers.append(current_teacher)

                current_teacher = Lecturer()
                current_teacher.name = line[2:].strip()
                content_lines = []
                self.pos += 1
                continue

            if line.startswith("  - "):
                content_lines.append(line[4:])
                self.pos += 1
                continue

            if line.startswith("    "):
                parsed_author = parse_author_line(line)
                if parsed_author is not None and current_teacher is not None:
                    review = SectionItem()
                    review.content = normalize_text("\n".join(content_lines))
                    if isinstance(parsed_author, list):
                        review.author = parsed_author
                    else:
                        review.author = parsed_author
                    if review.content or review.author:
                        current_teacher.reviews.append(review)
                    content_lines = []
                    self.pos += 1
                    continue
                content_lines.append(line[2:])
                self.pos += 1
                continue

            if not line.strip():
                self.pos += 1
                continue

            self.pos += 1

        if current_teacher:
            if content_lines:
                review = SectionItem()
                review.content = normalize_text("\n".join(content_lines))
                if review.content:
                    current_teacher.reviews.append(review)
            teachers.append(current_teacher)

        return teachers

    def _parse_multi_project_section(self, title: str) -> Section | None:
        """Parse a section within a multi-project course."""
        section = Section(title=title)
        current_item = SectionItem()
        content_lines: list[str] = []

        while self.pos < len(self.lines):
            line = self.lines[self.pos]

            if line.startswith("## ") or line.startswith("### "):
                break
            if line.strip() == "<!-- TOML-MISC -->":
                break

            parsed_author = parse_author_line(line)
            if parsed_author is not None:
                current_item.content = normalize_text("\n".join(content_lines))
                if isinstance(parsed_author, list):
                    current_item.author = parsed_author
                else:
                    current_item.author = parsed_author
                if current_item.content or current_item.author:
                    section.items.append(current_item)
                current_item = SectionItem()
                content_lines = []
                self.pos += 1
                continue

            content_lines.append(line)
            self.pos += 1

        if content_lines:
            current_item.content = normalize_text("\n".join(content_lines))
            if current_item.content:
                section.items.append(current_item)

        return section if section.items else None

    def _parse_multi_project_review_items(self, topic: str) -> list[SectionItem]:
        """Parse review items within a multi-project course review section.

        Similar to _parse_multi_project_section but returns flat list of
        SectionItem with topic set.
        """
        items: list[SectionItem] = []
        current_item = SectionItem(topic=topic)
        content_lines: list[str] = []

        while self.pos < len(self.lines):
            line = self.lines[self.pos]

            if line.startswith("## ") or line.startswith("### "):
                break
            if line.strip() == "<!-- TOML-MISC -->":
                break

            parsed_author = parse_author_line(line)
            if parsed_author is not None:
                current_item.content = normalize_text("\n".join(content_lines))
                if isinstance(parsed_author, list):
                    current_item.author = parsed_author
                else:
                    current_item.author = parsed_author
                if current_item.content or current_item.author:
                    items.append(current_item)
                current_item = SectionItem(topic=topic)
                content_lines = []
                self.pos += 1
                continue

            content_lines.append(line)
            self.pos += 1

        if content_lines:
            current_item.content = normalize_text("\n".join(content_lines))
            if current_item.content:
                items.append(current_item)

        return items

    def _parse_misc(self):
        """Parse misc section (e.g. MOOC) into doc.misc as list of content/author items.

        Note: misc content may contain embedded ### headers (e.g. ### 选课指南),
        so we only break on ## headers, not ### ones.
        """
        misc_items: list[dict] = []
        content_lines: list[str] = []

        while self.pos < len(self.lines):
            line = self.lines[self.pos]

            # Only break on ## (H2) headers — ### inside misc is content
            if line.startswith("## ") and not line.startswith("### "):
                break

            parsed_author = parse_author_line(line)
            if parsed_author is not None:
                content = normalize_text("\n".join(content_lines))
                item: dict = {}
                if content:
                    item["content"] = content
                if isinstance(parsed_author, list):
                    item["author"] = (
                        parsed_author[0] if len(parsed_author) == 1 else parsed_author
                    )
                else:
                    item["author"] = parsed_author
                if item:
                    misc_items.append(item)
                content_lines = []
                self.pos += 1
                continue

            content_lines.append(line)
            self.pos += 1

        if content_lines:
            content = normalize_text("\n".join(content_lines))
            if content:
                misc_items.append({"content": content})

        if misc_items:
            self.doc.misc = misc_items


# ============================================================================
# TOML Output
# ============================================================================


def format_toml_string(s: str) -> str:
    """Format a string for TOML output."""
    if not s:
        return '""'

    if "\n" in s:
        # Multiline: escape backslashes in content
        escaped = s.replace("\\", "\\\\")
        return '"""\n' + escaped + '\n"""'

    # Single line: escape special characters
    s = s.replace("\\", "\\\\")
    s = s.replace('"', '\\"')
    return f'"{s}"'


def format_toml_dict(d: dict, indent: int = 0) -> str:
    """Format a dict as inline TOML."""
    if not d:
        return "{}"

    parts = []
    for k, v in d.items():
        if isinstance(v, str):
            parts.append(f"{k} = {format_toml_string(v)}")
        elif isinstance(v, dict):
            parts.append(f"{k} = {format_toml_dict(v)}")
        elif v is None:
            parts.append(f'{k} = ""')
        else:
            parts.append(f"{k} = {v}")

    return "{ " + ", ".join(parts) + " }"


def generate_toml(doc: Document) -> str:
    """Generate TOML from document model."""
    lines = []

    # Top-level fields
    if doc.course_name:
        lines.append(f"course_name = {format_toml_string(doc.course_name)}")

    if doc.course_code:
        lines.append(f"course_code = {format_toml_string(doc.course_code)}")

    if doc.repo_type:
        lines.append(f"repo_type = {format_toml_string(doc.repo_type)}")

    # Description always output
    if doc.description:
        lines.append(f"description = {format_toml_string(doc.description)}")

    # Multi-project: output courses
    if doc.repo_type == "multi-project" and doc.courses:
        for course in doc.courses:
            lines.append("")
            lines.append("[[courses]]")
            if course.name:
                lines.append(f"name = {format_toml_string(course.name)}")
            if course.code:
                lines.append(f"code = {format_toml_string(course.code)}")

            # Course-level reviews (flat items with topic)
            for review in course.reviews:
                lines.append("")
                lines.append("[[courses.reviews]]")
                if review.topic:
                    lines.append(f"topic = {format_toml_string(review.topic)}")
                if review.content:
                    lines.append(f"content = {format_toml_string(review.content)}")
                _append_author_lines(lines, review)

            for teacher in course.teachers:
                lines.append("")
                lines.append("[[courses.teachers]]")
                lines.append(f"name = {format_toml_string(teacher.name)}")
                for review in teacher.reviews:
                    lines.append("")
                    lines.append("[[courses.teachers.reviews]]")
                    if review.content:
                        lines.append(f"content = {format_toml_string(review.content)}")
                    _append_author_lines(lines, review)

            for section in course.sections:
                lines.append("")
                lines.append("[[courses.sections]]")
                lines.append(f"title = {format_toml_string(section.title)}")
                for item in section.items:
                    lines.append("")
                    lines.append("[[courses.sections.items]]")
                    if item.content:
                        lines.append(f"content = {format_toml_string(item.content)}")
                    if item.topic:
                        lines.append(f"topic = {format_toml_string(item.topic)}")
                    _append_author_lines(lines, item)

        # Misc items (e.g., MOOC supplementary content)
        if doc.misc:
            misc_items = doc.misc if isinstance(doc.misc, list) else [doc.misc]
            for mi in misc_items:
                lines.append("")
                lines.append("[[misc]]")
                if isinstance(mi, dict):
                    if mi.get("content"):
                        lines.append(f"content = {format_toml_string(mi['content'])}")
                    author = mi.get("author")
                    if author:
                        if isinstance(author, Author):
                            lines.append(
                                f"author = {format_toml_dict(author.to_toml())}"
                            )
                        elif isinstance(author, dict):
                            lines.append(f"author = {format_toml_dict(author)}")

        return "\n".join(lines) + "\n"

    # Normal mode: basic info section
    basic_info_items = []
    if doc.credits:
        basic_info_items.append(f"【学分】: {doc.credits}")
    if doc.grading:
        basic_info_items.append(f"【成绩构成】: {doc.grading}")

    if basic_info_items:
        lines.append("")
        lines.append("[[sections]]")
        lines.append('title = "基本信息"')
        lines.append("")
        lines.append("[[sections.items]]")
        lines.append(f"content = {format_toml_string(chr(10).join(basic_info_items))}")

    # Lecturers (new schema)
    if not doc.lecturers.is_empty():
        lines.append("")
        lines.append("[lecturers]")

        for it in doc.lecturers.intro:
            lines.append("")
            lines.append("[[lecturers.intro]]")
            if it.content:
                lines.append(f"content = {format_toml_string(it.content)}")
            _append_author_lines(lines, it)

        for lec in doc.lecturers.items:
            lines.append("")
            lines.append("[[lecturers.items]]")
            lines.append(f"name = {format_toml_string(lec.name)}")

            for review in lec.reviews:
                lines.append("")
                lines.append("[[lecturers.items.reviews]]")
                if review.content:
                    lines.append(f"content = {format_toml_string(review.content)}")
                _append_author_lines(lines, review)

        for it in doc.lecturers.summary:
            lines.append("")
            lines.append("[[lecturers.summary]]")
            if it.content:
                lines.append(f"content = {format_toml_string(it.content)}")
            _append_author_lines(lines, it)

    # Sections
    for section in doc.sections:
        lines.append("")
        lines.append("[[sections]]")
        lines.append(f"title = {format_toml_string(section.title)}")

        for item in section.items:
            lines.append("")
            lines.append("[[sections.items]]")
            if item.content:
                lines.append(f"content = {format_toml_string(item.content)}")
            if item.topic:
                lines.append(f"topic = {format_toml_string(item.topic)}")
            _append_author_lines(lines, item)

    return "\n".join(lines) + "\n"


def _append_author_lines(lines: list[str], item: SectionItem) -> None:
    """Append author line(s) to TOML output."""
    if item.author is not None:
        if isinstance(item.author, list):
            author_parts = [format_toml_dict(a.to_toml()) for a in item.author]
            lines.append(f"author = [{', '.join(author_parts)}]")
        else:
            lines.append(f"author = {format_toml_dict(item.author.to_toml())}")
    elif item.has_author:
        lines.append('author = { name = "", link = "", date = "" }')


# ============================================================================
# CLI
# ============================================================================


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert README.md to readme.toml (bidirectional converter)"
    )
    parser.add_argument(
        "--input",
        "-i",
        required=True,
        help="Input README.md file or directory to scan",
    )
    parser.add_argument(
        "--output",
        "-o",
        help="Output TOML file (default: readme.toml in same directory)",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing TOML file",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Show detailed parsing information",
    )

    args = parser.parse_args()

    input_path = Path(args.input)

    if input_path.is_file():
        toml_paths = [input_path]
    else:
        toml_paths = sorted(input_path.rglob("README.md"))

    if not toml_paths:
        print("No README.md files found", file=sys.stderr)
        return 1

    for md_path in toml_paths:
        if args.output and len(toml_paths) == 1:
            out_path = Path(args.output)
        else:
            out_path = md_path.parent / "readme.toml"

        if out_path.exists() and not args.overwrite:
            print(f"Skipping {out_path} (use --overwrite to replace)")
            continue

        try:
            content = md_path.read_text(encoding="utf-8")
            parser_obj = MarkdownParser(content)
            doc = parser_obj.parse()
            toml_content = generate_toml(doc)

            out_path.write_text(toml_content, encoding="utf-8", newline="\n")
            print(f"Generated: {out_path}")

            if args.verbose:
                print(f"  Course: {doc.course_code} - {doc.course_name}")
                print(f"  Sections: {len(doc.sections)}")
                print(f"  Lecturers: {len(doc.lecturers.items)}")

        except Exception as e:
            print(f"Error processing {md_path}: {e}", file=sys.stderr)
            return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
